function equneq_instructions(currBlock, w)
% EQUNEQ_INSTRUCTIONS  Display instructions for ensembles task
%   currBlock (non-neg int): current block number
%   w (int): usable PsychToolbox window

% blank screen
Screen('FillRect', w, [0 0 0]);
Screen('Flip', w);

instText = [];

%Practice Instructions
if currBlock == 0 
    instText = ['Each trial will begin when your finger is in the starting position.\n\n'...
        'A fixation cross will appear, after which three shapes will appear.\n\n'...
         'The shape that is different from the others (e.g. tilted among level) \n\n'...
        'is your target.\n\n'...
        'If you respond correctly, you will hear a HIGH beep. \n\n\n\n'...
        'If you respond incorrectly, you will hear a LOW beep. \n\n\n\n'...
        'We will start with some practice trials. \n\n\n\n'...
        'POINT at the center of the target.'];
elseif currBlock ==  1
    instText = ['The practice block is now complete.\n\n'...
                'There will be several experimental blocks with breaks in between.\n\n'...
                'You will not see visual feedback anymore, but you will still hear beeps.\n\n\n\n'...
                'Press any key to continue to the next POINTING experimental block.\n\n'];
elseif currBlock == 10 
    instText = ['Each trial will begin when your finger is in the starting position.\n\n'...
        'A fixation cross will appear, after which three shapes will appear.\n\n'...
         'The shape that is different from the others (e.g. tilted among level) \n\n'...
        'is your target.\n\n'...
        'If you respond correctly, you will hear a HIGH beep. \n\n\n\n'...
        'If you respond incorrectly, you will hear a LOW beep. \n\n\n\n'...
        'We will start with some practice trials. \n\n\n\n'...
        'GRASP the pinch point with your index finger.'];
elseif currBlock ==  11
    instText = ['The practice block is now complete.\n\n'...
                'There will be several experimental blocks with breaks in between.\n\n'...
                'You will not see visual feedback anymore, but you will still hear beeps.\n\n\n\n'...
                'Press any key to continue to the next GRASPING experimental block.\n\n'];
elseif currBlock < 10
    instText = ['Press any key to continue to the next POINTING experimental block.\n\n'];

else
    instText = 'Press any key to continue to the next GRASPING experimental block.\n\n';
end

Screen('FillRect', w, [0 0 0]); % instruction screen background black
Screen('TextSize', w, []);
DrawFormattedText(w, instText, 'Center', 'Center', [255 255 255]);
Screen('Flip', w);  % display instructions
KbWait;  % wait for keypress
while KbCheck; end;  %% SS FIXME why
Screen('TextSize', w, 25);
Screen('Flip', w);  %% SS FIXME what's this doing?

